#ifndef MIS_CONVECIONES_H_INCLUDED
#define MIS_CONVECIONES_H_INCLUDED

#define TAMANIO 10
#define ARCHIVO_CORRUPTO -2
#define MAX_LINEAS 200000
enum boolean {true = 1, false = 0};

#endif // MIS_CONVECIONES_H_INCLUDED
